# Proyecto del Día 8 - Análisis de Datos Meteorológicos

Este proyecto consiste en analizar un conjunto de datos meteorológicos utilizando Python y NumPy. 
El objetivo es aplicar las técnicas de manipulación de arrays, tratamiento de datos faltantes, 
y análisis estadístico básico en un conjunto de datos del mundo real.

## Tareas a Realizar:
1. Crear un DataFrame a partir de los datos del archivo **datos_meteorologicos.csv** provisto en esta lección.
2. Realizar observaciones iniciales de los datos con Pandas.
3. Convertir las columnas del DataFrame en arrays de NumPy.
4. Identificar los datos faltantes en los arrays, y reemplazarlos por el promedio de los valores del respectivo array.
5. Realizar análisis estadísticos básicos. Mínimamente se espera que puedas extraer la siguiente información de tus arrays:
    * La temperatura promedio
    * El total de precipitaciones
    * La máxima humedad registrada
    * La fecha más calurosa
    * La fehca más fría
6. Exportar los resultados a un nuevo archivo CSV.

¡Mucha suerte con tu proyecto!

### 1. Crear un DataFrame a partir de los datos del archivo datos_meteorologicos.csv provisto en esta lección.

In [4]:
import pandas as pd
import numpy as np
ruta = r"C:\Users\Hogar\Desktop\Python-DataScience-y-Machine-Learning\Recursos\datos_meteorologicos.csv"
df = pd.read_csv(ruta)
df

           Fecha  Temperatura  Precipitación    Humedad
0     01/01/2010    17.440675      10.957482  52.384637
1     02/01/2010    25.759468       5.315628  30.633530
2     03/01/2010    20.138169      15.317706  41.496715
3     04/01/2010    17.244159      13.151008  90.684704
4     05/01/2010    11.182740      16.413667  22.116422
...          ...          ...            ...        ...
5105  24/12/2023    -9.554692      12.700998  50.094533
5106  25/12/2023     2.837831       5.475686  92.456057
5107  26/12/2023    29.873597       4.615012  18.362847
5108  27/12/2023          NaN            NaN        NaN
5109  28/12/2023    37.308043       7.330510  50.646211

[5110 rows x 4 columns]

### 2. Realizar observaciones iniciales de los datos con Pandas.

In [5]:
df.head()

        Fecha  Temperatura  Precipitación    Humedad
0  01/01/2010    17.440675      10.957482  52.384637
1  02/01/2010    25.759468       5.315628  30.633530
2  03/01/2010    20.138169      15.317706  41.496715
3  04/01/2010    17.244159      13.151008  90.684704
4  05/01/2010    11.182740      16.413667  22.116422

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Fecha          5110 non-null   object
 1   Temperatura    4855 non-null   float64
 2   Precipitación  4855 non-null   float64
 3   Humedad        4855 non-null   float64
dtypes: float64(3), object(1)
memory usage: 159.8+ KB

In [7]:
df.describe()

       Temperatura  Precipitación      Humedad
count  4855.000000    4855.000000  4855.000000
mean     14.889296       9.901604    54.359061
std      14.440466       5.801842    26.096345
min      -9.996378       0.003008    10.014980
25%       2.651777       4.756907    31.866578
50%      14.693274       9.853698    54.254478
75%      27.381451      14.966997    77.029500
max      39.998201      19.999559    99.996582

### 3. Convertir las columnas del DataFrame en arrays de NumPy.

In [10]:
temperatura = df['Temperatura'].to_numpy()
precipitacion = df['Precipitación'].to_numpy()
humedad = df['Humedad'].to_numpy()

### 4. Identificar los datos faltantes en los arrays, y reemplazarlos por el promedio de los valores del respectivo array.

In [12]:
temp_nulo = np.isnan(temperatura)
precip_nulo = np.isnan(precipitacion)
humed_nulo = np.isnan(humedad)

In [14]:
tem_promedio = np.nanmean(temperatura)
precip_promedio = np.nanmean(precipitacion)
humed_promedio = np.nanmean(humedad)

temperatura[temp_nulo] = tem_promedio
precipitacion[temp_nulo] = precip_promedio
humedad[temp_nulo] = humed_promedio

### 5. Realizar análisis estadísticos básicos.

##### Temperatura promedio

In [15]:
temp_promedio = np.nanmean(temperatura)
temp_promedio

np.float64(14.889295723531713)

##### Total de precipitaciones

In [18]:
precip_maxima = np.sum(precipitacion)
precip_maxima

np.float64(50597.19438939993)

##### Máxima humedad registrada

In [19]:
humedad_maxima = np.max(humedad)
humedad_maxima

np.float64(99.99658156071747)

##### Fecha más calurosa

In [20]:
mas_calor = np.max(temperatura)
mas_calor

np.float64(39.99820092713012)

In [23]:
# Sacamos el índice para poder sacar la fecha
registro_mas_caluroso = np.where(temperatura == mas_calor)[0][0]
registro_mas_caluroso

np.int64(2749)

In [24]:
# Podemos filtrar la fecha
fecha_mas_calurosa = df.iloc[registro_mas_caluroso]['Fecha']
fecha_mas_calurosa

'12/07/2017'

##### Fecha más fría

In [28]:
fecha_mas_fria = df.iloc[np.where(temperatura == np.min(temperatura))[0][0]]['Fecha']
fecha_mas_fria

'23/07/2020'

### 6. Exportar los resultados a un nuevo archivo CSV.