In [6]:
import pandas as pd

data = {
        "Id_producto": [1001, 1002, 1003, 1003],
           "Cantidad_vendida": [30, None, 25, 25],
            "Precio": [20.5, 15.0, None, 22.5]
       }

df = pd.DataFrame(data)
df

   Id_producto  Cantidad_vendida  Precio
0         1001              30.0    20.5
1         1002               NaN    15.0
2         1003              25.0     NaN
3         1003              25.0    22.5

In [24]:
#Se realiza para ver los primeros datos de la tabla
df.head()

   Id_producto  Cantidad_vendida  Precio
0         1001              30.0    20.5
1         1002               NaN    15.0
2         1003              25.0     NaN
3         1003              25.0    22.5

In [25]:
# Se realiza para conocer la información del dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id_producto       4 non-null      int64
 1   Cantidad_vendida  3 non-null      float64
 2   Precio            3 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 228.0 bytes

In [26]:
# Identifica los nulos
df.isnull()

   Id_producto  Cantidad_vendida  Precio
0        False             False   False
1        False              True   False
2        False             False    True
3        False             False   False

In [27]:
# Suma los nulos que hay en el dataframe
df.isnull().sum()

Id_producto         0
Cantidad_vendida    1
Precio              1
dtype: int64

In [28]:
# Elimina los nulos por completo con su fila
df_eliminados = df.dropna()
df_eliminados

   Id_producto  Cantidad_vendida  Precio
0         1001              30.0    20.5
3         1003              25.0    22.5

In [29]:
# Saca un promedio de la serie mencionada para llenar el campo null
valores_nuevos = {"Cantidad_vendida": 0, "Precio": df["Precio"].mean()}
df_rellenados = df.fillna(valores_nuevos)
df_rellenados

   Id_producto  Cantidad_vendida     Precio
0         1001              30.0  20.500000
1         1002               0.0  15.000000
2         1003              25.0  19.333333
3         1003              25.0  22.500000

In [37]:
# Se realiza un cambio de tipo para ir limpiando los datos
df_rellenados["Cantidad_vendida"] = df_rellenados["Cantidad_vendida"].astype(int)
df_rellenados

   Id_producto  Cantidad_vendida     Precio
0         1001                30  20.500000
1         1002                 0  15.000000
2         1003                25  19.333333
3         1003                25  22.500000

In [39]:
# Se elimina los datos duplicados de una serie en específico
df_unicos = df_rellenados.drop_duplicates(subset=["Id_producto", "Cantidad_vendida"])
df_unicos

   Id_producto  Cantidad_vendida     Precio
0         1001                30  20.500000
1         1002                 0  15.000000
2         1003                25  19.333333