In [1]:
import pandas as pd

In [4]:
datos = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Sara'],
    'Edad': [25, 30, 22, 27],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Bilbao']
}

df = pd.DataFrame(datos)

In [5]:
df

   Nombre  Edad     Ciudad
0     Ana    25     Madrid
1    Luis    30  Barcelona
2  Carlos    22   Valencia
3    Sara    27     Bilbao

In [7]:
# Agregar una nueva columna

df['Salarios'] = [30000, 45000, 38000, 32000]
df

   Nombre  Edad     Ciudad  Salarios
0     Ana    25     Madrid     30000
1    Luis    30  Barcelona     45000
2  Carlos    22   Valencia     38000
3    Sara    27     Bilbao     32000

In [9]:
# Modificar la columna de un df
df['Salarios'] = df['Salarios'] + 2000
df

   Nombre  Edad     Ciudad  Salarios
0     Ana    25     Madrid     32000
1    Luis    30  Barcelona     47000
2  Carlos    22   Valencia     40000
3    Sara    27     Bilbao     34000

In [10]:
# Seleccionar una columna y almacenarla en una variable
nombres = df['Nombre']
nombres

0       Ana
1      Luis
2    Carlos
3      Sara
Name: Nombre, dtype: object

In [11]:
# Aplicar un método de filtrado
mayores_25 = df[df['Edad'] > 25]
mayores_25

  Nombre  Edad     Ciudad  Salarios
1   Luis    30  Barcelona     47000
3   Sara    27     Bilbao     34000

In [12]:
# Hacer lo mismo pero con variables
edades = df['Edad']
edades

0    25
1    30
2    22
3    27
Name: Edad, dtype: int64

In [13]:
mayores_25 = df[edades > 25]
mayores_25

  Nombre  Edad     Ciudad  Salarios
1   Luis    30  Barcelona     47000
3   Sara    27     Bilbao     34000

In [14]:
# Tipos de datos con los que estamos trabajando
type(df)

pandas.core.frame.DataFrame

In [15]:
type(edades)

pandas.core.series.Series

In [16]:
type(mayores_25)

pandas.core.frame.DataFrame

In [19]:
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Sara'],
    'Edad': [25, 30, 22, 27],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Bilbao']
}

df = pd.DataFrame(data)
edades = df['Edad']
df_filtrado = df[edades >= 25]
df_filtrado

  Nombre  Edad     Ciudad
0    Ana    25     Madrid
1   Luis    30  Barcelona
3   Sara    27     Bilbao

In [38]:
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Sara'],
    'Edad': [25, 30, 22, 27],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Bilbao']
}

df = pd.DataFrame(data)
df['Edad_en_10_años'] = df['Edad'] + 10
df['Ciudad'] = df['Ciudad'].str.upper()
df['Es_Mayor_de_25'] = df['Edad'] >= 25
df

   Nombre  Edad     Ciudad  Edad_en_10_años  Es_Mayor_de_25
0     Ana    25     MADRID               35            True
1    Luis    30  BARCELONA               40            True
2  Carlos    22   VALENCIA               32           False
3    Sara    27     BILBAO               37            True