In [8]:
import pandas as pd

In [9]:
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Nombre': ['Ana', 'Luis', 'Carlos']
})

df2 = pd.DataFrame({
    'ID': [1, 2, 4],
    'Edad': [25, 30, 22]
})

In [10]:
df1

   ID  Nombre
0   1     Ana
1   2    Luis
2   3  Carlos

In [11]:
df2

   ID  Edad
0   1    25
1   2    30
2   4    22

In [13]:
# Mostrar solo los argumentos que coinciden con el ID
df_combinado = pd.merge(df1, df2, on='ID', how='inner')
df_combinado

   ID Nombre  Edad
0   1    Ana    25
1   2   Luis    30

In [14]:
# Muestra todo los datos y se le asigna NaN a los datos que no coinciden
df_combinado = pd.merge(df1, df2, on='ID', how='outer')
df_combinado

   ID  Nombre  Edad
0   1     Ana  25.0
1   2    Luis  30.0
2   3  Carlos   NaN
3   4     NaN  22.0

In [15]:
# Pandas incluye todos los datos de la tabla izquierda que en este caso es df1
df_combinado = pd.merge(df1, df2, on='ID', how='left')
df_combinado

   ID  Nombre  Edad
0   1     Ana  25.0
1   2    Luis  30.0
2   3  Carlos   NaN

In [17]:
# Pandas incluye todos los datos de la tabla derecha que en este caso es df2
df_combinado = pd.merge(df1, df2, on='ID', how='right')
df_combinado

   ID Nombre  Edad
0   1    Ana    25
1   2   Luis    30
2   4    NaN    22

In [19]:
# Lo que hace es poner los df uno al lado del otro para comprender de donde vienen los datos y sus indices
df_indexado = pd.merge(df1, df2, left_index=True, right_index=True)
df_indexado

   ID_x  Nombre  ID_y  Edad
0     1     Ana     1    25
1     2    Luis     2    30
2     3  Carlos     4    22

In [21]:
libros = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'titulo': ['El Quijote', 'La Odisea', 'Cien Años de Soledad', 'El Principito']
})

autores = pd.DataFrame({
    'ID': [1, 2, 3, 5],
    'nombre': ['Miguel de Cervantes', 'Homero', 'Gabriel García Márquez', 'J.K. Rowling']
})

libros_autores = pd.merge(libros, autores, how='outer')
libros_autores

   ID                titulo                  nombre
0   1            El Quijote     Miguel de Cervantes
1   2             La Odisea                  Homero
2   3  Cien Años de Soledad  Gabriel García Márquez
3   4         El Principito                     NaN
4   5                   NaN            J.K. Rowling

In [33]:
cursos = pd.DataFrame({
    'curso_id': [101, 102, 103],
    'nombre_curso': ['Introducción a Python', 'Data Science con Python', 'Machine Learning Avanzado']
})

inscripciones = pd.DataFrame({
    'curso_id': [102, 102, 101, 104],
    'fecha_inscripcion': ['2023-01-15', '2023-02-01', '2023-01-20', '2023-03-05']
})

cursos_inscripciones = pd.merge(inscripciones, cursos, on='curso_id', how='left')
cursos_inscripciones

   curso_id fecha_inscripcion             nombre_curso
0       102        2023-01-15  Data Science con Python
1       102        2023-02-01  Data Science con Python
2       101        2023-01-20    Introducción a Python
3       104        2023-03-05                      NaN

In [35]:
productos = pd.DataFrame({
    'ID': [10, 11, 12],
    'Nombre': ['Teclado', 'Mouse', 'Monitor'],
    'Marca': ['Logitech', 'Razer', 'Dell']
})

reviews = pd.DataFrame({
    'ID': [10, 11, 12],
    'Calificación': [5, 4, 4],
    'Comentario': ['Excelente producto', 'Buen producto', 'Satisfecho']
})

productos_reviews = pd.merge(productos, reviews, left_index=True, right_index=True)
productos_reviews

   ID_x   Nombre     Marca  ID_y  Calificación          Comentario
0    10  Teclado  Logitech    10             5  Excelente producto
1    11    Mouse     Razer    11             4       Buen producto
2    12  Monitor      Dell    12             4          Satisfecho