In [2]:
import pandas as pd

In [8]:
df1 = pd.DataFrame({
    'Salario': [30000, 45000, 38000],
    'Antiguedad': [9, 13, 12]},
    index=[1,2,3])

df2 = pd.DataFrame({
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia'],
    'Jerarquía': ['Baja', 'Media', 'Alta']},
    index=[1,2,4])

In [5]:
df1

   Salrio  Antiguedad
1   30000           9
2   45000          13
3   38000          12

In [6]:
df2

      Ciudad Jerarquía
1     Madrid      Baja
2  Barcelona     Media
4   Valencia      Alta

In [9]:
# Se conserva la columna izquierda, el join viene por defecto con el how left
df_unido = df1.join(df2)
df_unido

   Salario  Antiguedad     Ciudad Jerarquía
1    30000           9     Madrid      Baja
2    45000          13  Barcelona     Media
3    38000          12        NaN       NaN

In [12]:
df_unido = df1.join(df2, how='inner')
df_unido

   Salario  Antiguedad     Ciudad Jerarquía
1    30000           9     Madrid      Baja
2    45000          13  Barcelona     Media

In [13]:
# Creación del DataFrame df_a
df_a = pd.DataFrame({
    'id': [1, 2, 3],
    'Nombre': ['Ana', 'Beto', 'Carla']
})
df_a.set_index('id', inplace=True)

# Creación del DataFrame df_b
df_b = pd.DataFrame({
    'id': [1, 2, 3],
    'Edad': [25, 30, 35]
})
df_b.set_index('id', inplace=True)

df_combinado = df_a.join(df_b)
df_combinado

   Nombre  Edad
id
1     Ana    25
2    Beto    30
3   Carla    35

In [25]:
productos_df = pd.DataFrame({
    'ProductoID': [1, 2, 3, 4],
    'Nombre': ['Producto 1', 'Producto 2', 'Producto 3', 'Producto 4'],
    'Precio': [100, 150, 200, 250]
}).set_index('ProductoID')

categorias_df = pd.DataFrame({
    'CategoriaID': [1, 2],
    'NombreCategoria': ['Categoría 1', 'Categoría 2']
}).set_index('CategoriaID')

df_combinado = productos_df.join(categorias_df)
df_combinado

                Nombre  Precio NombreCategoria
ProductoID
1           Producto 1     100     Categoría 1
2           Producto 2     150     Categoría 2
3           Producto 3     200             NaN
4           Producto 4     250             NaN

In [27]:
productos_df = pd.DataFrame({
    'ProductoID': [1, 2, 3, 4],
    'Nombre': ['Producto 1', 'Producto 2', 'Producto 3', 'Producto 4'],
    'Precio': [100, 150, 200, 250]
})

productos_df = productos_df.set_index('ProductoID')

categorias_df = pd.DataFrame({
    'CategoriaID': [1, 2, 3],
    'NombreCategoria': ['Categoría 1', 'Categoría 2', 'Categoría 3']
}).set_index('CategoriaID')

df_combinado = categorias_df.join(productos_df, how='right')
df_combinado

           NombreCategoria      Nombre  Precio
ProductoID
1              Categoría 1  Producto 1     100
2              Categoría 2  Producto 2     150
3              Categoría 3  Producto 3     200
4                      NaN  Producto 4     250