In [4]:
import pandas as pd

In [9]:
# Se muestra un rango de fecha por día
fechas = pd.Series(pd.date_range('20240101', periods=6))
fechas

0   2024-01-01
1   2024-01-02
2   2024-01-03
3   2024-01-04
4   2024-01-05
5   2024-01-06
dtype: datetime64[ns]

In [8]:
type(fechas[0])

pandas._libs.tslibs.timestamps.Timestamp

In [10]:
# Este es el parámetro que viene por defecto para freq por eso no salta años ni meses, solo por día a día
fechas = pd.Series(pd.date_range('20240101', periods=6, freq='D'))
fechas

0   2024-01-01
1   2024-01-02
2   2024-01-03
3   2024-01-04
4   2024-01-05
5   2024-01-06
dtype: datetime64[ns]

In [12]:
# Va a hacer saltos mes por mes
fechas = pd.Series(pd.date_range('20240101', periods=6, freq='ME'))
fechas

0   2024-01-31
1   2024-02-29
2   2024-03-31
3   2024-04-30
4   2024-05-31
5   2024-06-30
dtype: datetime64[ns]

In [14]:
# Va a hacer saltos año en año
fechas = pd.Series(pd.date_range('20240101', periods=6, freq='YE'))
fechas

0   2024-12-31
1   2025-12-31
2   2026-12-31
3   2027-12-31
4   2028-12-31
5   2029-12-31
dtype: datetime64[ns]

In [16]:
# Va a hacer saltos hora en hora
fechas = pd.Series(pd.date_range('20240101', periods=6, freq='h'))
fechas

0   2024-01-01 00:00:00
1   2024-01-01 01:00:00
2   2024-01-01 02:00:00
3   2024-01-01 03:00:00
4   2024-01-01 04:00:00
5   2024-01-01 05:00:00
dtype: datetime64[ns]

In [19]:
# Va a hacer saltos minuto en minuto
fechas = pd.Series(pd.date_range('20240101', periods=6, freq='min'))
fechas

0   2024-01-01 00:00:00
1   2024-01-01 00:01:00
2   2024-01-01 00:02:00
3   2024-01-01 00:03:00
4   2024-01-01 00:04:00
5   2024-01-01 00:05:00
dtype: datetime64[ns]

In [20]:
# Va a hacer saltos de a días
fechas = pd.Series(pd.date_range('20240101', periods=6, freq='5D'))
fechas

0   2024-01-01
1   2024-01-06
2   2024-01-11
3   2024-01-16
4   2024-01-21
5   2024-01-26
dtype: datetime64[ns]

In [23]:
# convertir de tipo de datos a fecha
ruta = r"C:\Users\Daniel\Desktop\Python para Data Science & Machine Learning\Recursos\Mercado+de+Valores+España.csv"
df = pd.read_csv(ruta)
df

,Ticker,Fecha,Cierre,Referencia,Volumen,Rotacion,Ultimo,Alto,Bajo,Promedio
0,ANA,02/01/2019,74.80,73.90,156300,11621188.98,74.80,75.16,72.38,74.3518
1,ANA,03/01/2019,76.34,74.80,140331,10632703.64,76.34,76.60,74.54,75.7687
2,ANA,04/01/2019,76.62,76.34,130309,10010838.76,76.62,77.40,76.40,76.8162
3,ANA,07/01/2019,77.14,76.62,63349,4855724.92,77.14,77.30,75.62,76.6504
4,ANA,08/01/2019,78.24,77.14,99300,7749464.70,78.24,78.46,77.00,78.0409
...,...,...,...,...,...,...,...,...,...,...
8570,VIS,09/12/2019,48.70,48.76,40236,1958325.66,48.70,48.96,48.44,48.6710
8571,VIS,10/12/2019,48.16,48.70,60198,2895965.78,48.16,48.74,47.70,48.1201
8572,VIS,11/12/2019,47.96,48.16,63000,3012462.12,47.96,48.42,47.52,47.8169
8573,VIS,12/12/2019,48.42,47.96,50218,2429199.80,48.42,48.66,47.76,48.3731
8574,VIS,13/12/2019,48.64,48.42,62427,3038685.10,48.64,49.18,48.12,48.6758

In [27]:
df['Fecha'][0]

'02/01/2019'

In [28]:
type(df['Fecha'][0])

str

In [30]:
df['Fecha'] = pd.to_datetime(df['Fecha'], format='%d/%m/%Y')
df

,Ticker,Fecha,Cierre,Referencia,Volumen,Rotacion,Ultimo,Alto,Bajo,Promedio
0,ANA,2019-01-02,74.80,73.90,156300,11621188.98,74.80,75.16,72.38,74.3518
1,ANA,2019-01-03,76.34,74.80,140331,10632703.64,76.34,76.60,74.54,75.7687
2,ANA,2019-01-04,76.62,76.34,130309,10010838.76,76.62,77.40,76.40,76.8162
3,ANA,2019-01-07,77.14,76.62,63349,4855724.92,77.14,77.30,75.62,76.6504
4,ANA,2019-01-08,78.24,77.14,99300,7749464.70,78.24,78.46,77.00,78.0409
...,...,...,...,...,...,...,...,...,...,...
8570,VIS,2019-12-09,48.70,48.76,40236,1958325.66,48.70,48.96,48.44,48.6710
8571,VIS,2019-12-10,48.16,48.70,60198,2895965.78,48.16,48.74,47.70,48.1201
8572,VIS,2019-12-11,47.96,48.16,63000,3012462.12,47.96,48.42,47.52,47.8169
8573,VIS,2019-12-12,48.42,47.96,50218,2429199.80,48.42,48.66,47.76,48.3731
8574,VIS,2019-12-13,48.64,48.42,62427,3038685.10,48.64,49.18,48.12,48.6758

In [31]:
df['Fecha'][0]

Timestamp('2019-01-02 00:00:00')

In [32]:
type(df['Fecha'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [33]:
df['Fecha'][44]

Timestamp('2019-03-05 00:00:00')

In [34]:
df['Fecha'][44].year

2019

In [35]:
df['Fecha'][44].month

3

In [36]:
df['Fecha'][44].day

5

In [37]:
df_mas_5_dias = df['Fecha'] + pd.Timedelta(days=5)
df_mas_5_dias

0      2019-01-07
1      2019-01-08
2      2019-01-09
3      2019-01-12
4      2019-01-13
          ...
8570   2019-12-14
8571   2019-12-15
8572   2019-12-16
8573   2019-12-17
8574   2019-12-18
Name: Fecha, Length: 8575, dtype: datetime64[ns]