In [1]:
import pandas as pd

In [4]:
df = pd.DataFrame({
    'Col1': [100, 200, 300],
    'Col2': [400, 500, 600],
    'Col3': [700, 800, 900]
}, index=['fila1', 'fila2', 'fila3'])
df

       Col1  Col2  Col3
fila1   100   400   700
fila2   200   500   800
fila3   300   600   900

In [17]:
# Loc nos permite filtrar por filas o columnas basandose en sus etiquetas
# Nos sirve para seleccionar filas y sus respectivas columnas
df.loc['fila1']

Col1    100
Col2    400
Col3    700
Name: fila1, dtype: int64

In [7]:
type(df.loc['fila1'])

pandas.core.series.Series

In [10]:
# Para traer dos filas se debe ingresar doble llaves cuadradas
df.loc[['fila1', 'fila3']]

       Col1  Col2  Col3
fila1   100   400   700
fila3   300   600   900

In [11]:
type(df.loc[['fila1', 'fila3']])

pandas.core.frame.DataFrame

In [13]:
# Buscar las filas como segmentación
df.loc['fila2':'fila3']

       Col1  Col2  Col3
fila2   200   500   800
fila3   300   600   900

In [14]:
# Pasar una lista de booleanos
df.loc[[False, True, False]]

       Col1  Col2  Col3
fila2   200   500   800

In [15]:
# Algunas filas que cumplan una condición particular
df.loc[df['Col1'] > 150]

       Col1  Col2  Col3
fila2   200   500   800
fila3   300   600   900

In [16]:
# Y si queremos trar columnas en ves de filas
df.loc[:, ['Col1', 'Col2']]

       Col1  Col2
fila1   100   400
fila2   200   500
fila3   300   600

In [19]:
# iloc se basa en las pocisiones numéricas
df.iloc[0]

Col1    100
Col2    400
Col3    700
Name: fila1, dtype: int64

In [21]:
# Los : puntos indican las filas, ahí le decimos que me pase todas las filas y despues de la , cuantas columnas quiero que me traiga
df.iloc[:, [0,1]]

       Col1  Col2
fila1   100   400
fila2   200   500
fila3   300   600

In [22]:
df.iloc[1:3]

       Col1  Col2  Col3
fila2   200   500   800
fila3   300   600   900

In [23]:
df = pd.DataFrame({
    'Nombre': ['Ana', 'Luis', 'Carmen'],
    'Edad': [25, 30, 22],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia']
}, index=['fila1', 'fila2', 'fila3'])

df.loc['fila2']

Nombre         Luis
Edad             30
Ciudad    Barcelona
Name: fila2, dtype: object

In [33]:
import pandas as pd
df = pd.DataFrame({
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12],
    'D': [13, 14, 15, 16]
})

resultado = df.iloc[:2, [2,3]]
resultado

    C   D
0   9  13
1  10  14