In [1]:
import pandas as pd

In [6]:
ventas1 = pd.read_csv(r'C:\Users\Hogar\Desktop\Python-DataScience-y-Machine-Learning\Recursos\Datos_Ventas_Tienda.csv')
ventas2 = pd.read_csv(r'C:\Users\Hogar\Desktop\Python-DataScience-y-Machine-Learning\Recursos\Datos_Ventas_Tienda2.csv')

In [27]:
# 1.Lectura de Datos:
ventas1

         Fecha    Producto  Cantidad  Precio Unitario  Total Venta
0    1/17/2023  Electrónic         7              200         1400
1     9/1/2023  Electrónic         8              200         1600
2    7/29/2023    Juguetes         3               30           90
3    10/4/2023   Alimentos         4               10           40
4    2/28/2023  Electrónic         6              200         1200
..         ...         ...       ...              ...          ...
995  4/27/2023   Alimentos         2               10           20
996   6/9/2023        Ropa        10               50          500
997  8/21/2023   Alimentos         8               10           80
998  3/28/2023  Electrónic         6              200         1200
999   3/7/2023  Electrónic         4              200          800

[1000 rows x 5 columns]

In [16]:
# Muestra las primeras 5 filas del dataset
ventas1.head()

       Fecha    Producto  Cantidad  Precio Unitario  Total Venta
0  1/17/2023  Electrónic         7              200         1400
1   9/1/2023  Electrónic         8              200         1600
2  7/29/2023    Juguetes         3               30           90
3  10/4/2023   Alimentos         4               10           40
4  2/28/2023  Electrónic         6              200         1200

In [17]:
# Mirar cuántas Filas y columnas tiene el dataset, con eso sabemos el tamaño del dataset
ventas1.shape

(1000, 5)

In [19]:
# Nos permite un resumen técnico del dataframe
ventas1.info

<bound method DataFrame.info of          Fecha    Producto  Cantidad  Precio Unitario  Total Venta
0    1/17/2023  Electrónic         7              200         1400
1     9/1/2023  Electrónic         8              200         1600
2    7/29/2023    Juguetes         3               30           90
3    10/4/2023   Alimentos         4               10           40
4    2/28/2023  Electrónic         6              200         1200
..         ...         ...       ...              ...          ...
995  4/27/2023   Alimentos         2               10           20
996   6/9/2023        Ropa        10               50          500
997  8/21/2023   Alimentos         8               10           80
998  3/28/2023  Electrónic         6              200         1200
999   3/7/2023  Electrónic         4              200          800

[1000 rows x 5 columns]>

In [21]:
# Genera estadística descriptiva, media, desviación estándar, mínimo, máximo
ventas1.describe()

          Cantidad  Precio Unitario  Total Venta
count  1000.000000      1000.000000  1000.000000
mean      5.500000        64.140000   350.650000
std       2.892467        72.345658   477.861936
min       1.000000        10.000000    10.000000
25%       3.000000        20.000000    70.000000
50%       5.000000        30.000000   150.000000
75%       8.000000        50.000000   400.000000
max      10.000000       200.000000  2000.000000

In [23]:
# Nos permite ver los valores vacíos por columna 
ventas1.isnull().sum()

Fecha              0
Producto           0
Cantidad           0
Precio Unitario    0
Total Venta        0
dtype: int64

In [24]:
# Nos permite ver cuantas filas hay duplicadas
ventas1.duplicated().sum()

np.int64(27)

In [25]:
# Muestra los nombres de las columnas
ventas1.columns

Index(['Fecha', 'Producto', 'Cantidad', 'Precio Unitario', 'Total Venta'], dtype='object')

In [8]:
ventas2

         Fecha    Producto  Cantidad  Precio Unitario  Total Venta
0    8/25/2023  Electrónic         5              200         1000
1    8/14/2023   Alimentos         9               10           90
2    8/30/2023        Ropa         6               50          300
3    11/9/2023   Alimentos         2               10           20
4   10/26/2023        Ropa         8               50          400
5    12/1/2023    Juguetes         2               30           60
6    5/16/2023  Electrónic         4              200          800
7     2/9/2023      Libros         1               20           20
8     1/9/2023  Electrónic         2              200          400
9     5/3/2023  Electrónic         6              200         1200
10  11/30/2023  Electrónic         5              200         1000
11  10/26/2023  Electrónic         1              200          200
12   8/22/2023    Juguetes         3               30           90
13    6/5/2023  Electrónic         1              200          200
14   10/2/2023    Juguetes         6               30          180
15   1/25/2023  Electrónic         3              200          600
16   5/20/2023        Ropa         4               50          200
17   4/29/2023   Alimentos         8               10           80
18  12/20/2023        Ropa         2               50          100
19   4/10/2023        Ropa         8               50          400
20   5/19/2023    Juguetes         5               30          150
21    2/3/2023  Electrónic         4              200          800
22    3/4/2023        Ropa         5               50          250
23  11/12/2023    Juguetes         7               30          210
24   5/22/2023      Libros         7               20          140
25  11/19/2023        Ropa         4               50          200
26   7/31/2023   Alimentos         6               10           60
27  10/11/2023        Ropa         6               50          300
28   12/9/2023    Juguetes         4               30          120
29    3/6/2023      Libros         9               20          180
30   3/27/2023   Alimentos         1               10           10
31   4/23/2023        Ropa         9               50          450
32   5/26/2023  Electrónic         6              200         1200
33   1/20/2023    Juguetes         5               30          150
34   3/22/2023   Alimentos         9               10           90
35   2/26/2023      Libros         9               20          180
36   7/30/2023    Juguetes         1               30           30
37  11/18/2023        Ropa         3               50          150
38   6/20/2023      Libros         8               20          160
39    6/6/2023      Libros         3               20           60
40    5/2/2023   Alimentos         5               10           50
41    8/7/2023  Electrónic         9              200         1800
42  11/18/2023    Juguetes         8               30          240
43   1/17/2023    Juguetes         8               30          240
44  10/10/2023      Libros         6               20          120
45   9/11/2023    Juguetes        10               30          300
46    1/3/2023    Juguetes        10               30          300
47   11/7/2023   Alimentos         3               10           30
48   8/20/2023  Electrónic         6              200         1200
49   7/21/2023    Juguetes         3               30           90

In [31]:
ventas2.shape

(50, 5)

In [32]:
ventas2.columns

Index(['Fecha', 'Producto', 'Cantidad', 'Precio Unitario', 'Total Venta'], dtype='object')

In [30]:
# 2.Fusión de Datos:
ventas_concatenada = pd.concat([ventas1, ventas2])
ventas_concatenada

        Fecha    Producto  Cantidad  Precio Unitario  Total Venta
0   1/17/2023  Electrónic         7              200         1400
1    9/1/2023  Electrónic         8              200         1600
2   7/29/2023    Juguetes         3               30           90
3   10/4/2023   Alimentos         4               10           40
4   2/28/2023  Electrónic         6              200         1200
..        ...         ...       ...              ...          ...
45  9/11/2023    Juguetes        10               30          300
46   1/3/2023    Juguetes        10               30          300
47  11/7/2023   Alimentos         3               10           30
48  8/20/2023  Electrónic         6              200         1200
49  7/21/2023    Juguetes         3               30           90

[1050 rows x 5 columns]

In [34]:
# 3.Tratamiento de Datos:
ventas_concatenada.shape

(1050, 5)

In [38]:
ventas_concatenada.isnull().sum()

Fecha              0
Producto           0
Cantidad           0
Precio Unitario    0
Total Venta        0
dtype: int64

In [39]:
ventas_concatenada.info

<bound method DataFrame.info of         Fecha    Producto  Cantidad  Precio Unitario  Total Venta
0   1/17/2023  Electrónic         7              200         1400
1    9/1/2023  Electrónic         8              200         1600
2   7/29/2023    Juguetes         3               30           90
3   10/4/2023   Alimentos         4               10           40
4   2/28/2023  Electrónic         6              200         1200
..        ...         ...       ...              ...          ...
45  9/11/2023    Juguetes        10               30          300
46   1/3/2023    Juguetes        10               30          300
47  11/7/2023   Alimentos         3               10           30
48  8/20/2023  Electrónic         6              200         1200
49  7/21/2023    Juguetes         3               30           90

[1050 rows x 5 columns]>

In [40]:
ventas_concatenada.describe()

          Cantidad  Precio Unitario  Total Venta
count  1050.000000      1050.000000  1050.000000
mean      5.490476        64.428571   349.761905
std       2.882577        72.437522   473.870983
min       1.000000        10.000000    10.000000
25%       3.000000        20.000000    70.000000
50%       5.000000        30.000000   150.000000
75%       8.000000        50.000000   400.000000
max      10.000000       200.000000  2000.000000

In [44]:
# 4.Análisis de Ventas:
# ¿Cuál es el producto más vendido?
mas_vendido = ventas_concatenada['Producto'].value_counts()
mas_vendido

Producto
Electrónic    227
Alimentos     224
Juguetes      206
Ropa          199
Libros        194
Name: count, dtype: int64

In [52]:
# ¿Cuál es el mes con mas ventas?
mes_mas_ventas = ventas_concatenada.groupby('Fecha')['Total Venta'].sum().sort_values(ascending=False)
mes_mas_ventas

Fecha
5/14/2023     5790
2/28/2023     5640
1/12/2023     4680
8/29/2023     4400
7/20/2023     4160
              ...
12/4/2023       30
6/3/2023        20
11/11/2023      20
11/15/2023      20
6/13/2023       10
Name: Total Venta, Length: 346, dtype: int64

In [49]:
# 5.Datos Agrupados:
agrupar_categoria_producto = ventas_concatenada.groupby('Producto')['Total Venta'].sum().sort_values(ascending=False)
agrupar_categoria_producto

Producto
Electrónic    244000
Ropa           56400
Juguetes       33390
Libros         20840
Alimentos      12620
Name: Total Venta, dtype: int64

In [51]:
ventas_concatenada.to_csv(r"C:\Users\Hogar\Desktop\Python-DataScience-y-Machine-Learning\Recursos\Ventas_Concatenadas.csv", index=False)